### ISSUE TITLE
Revert forcing the font to Google Sans Text

### ISSUE THREAD

**Issue by Dionicio3** [DerTyp7214/RboardThemeManagerV3#161]
Hey, I noticed that recently my Gboard was using Google Sans Text instead of Roboto, which usually happens after an update. I went into Rboard to quickly fix this, but no matter what I did, it's still suck as Google Sans Text. So I came here and saw that there was recently a change to force this. Do you think this can be reverted? Thanks

**Comment by AkosPaha** [comment]
Rboard has nothing to do with Gboard's Font. Google Sans Text is forced into Rboard, not anywhere else.

**Comment by Dionicio3** [comment]
Oh my bad. Yeah keyboard_redesign_google_sans is off, but even after reloading multiple times, it's still using Google Sans Text. My Gboard is on version 12.4.03.482060964-beta-arm64-v8a if that helps
