### ISSUE TITLE
[REQUEST] Add option to keep system font

### ISSUE THREAD

**Issue by xerta555** [DerTyp7214/RboardThemeManagerV3#167]
Hi

It could be possible to add an option to keep system font ?
I ask that bcz i don't like the google font, so i have apply a custom font on my device, but the google one have been forced in a recent update.

Thanks to add an option to keep the system font, to let the user decide.

**Comment by DerTyp7214** [comment]
no

**Comment by xerta555** [comment]
> no.

Since your answer was very brief, i know that it is possible to add this option in an application like this.
Could you please tell me why you don't want to add this option?

**Comment by DerTyp7214** [comment]
Because users usually installing super ugly fonts that breaks app

**Comment by xerta555** [comment]
> Because users usually installing super ugly fonts that breaks app

I completely understand your point of view.
However, there are other fonts that don't come from Google and that work perfectly with any Android application, hence my proposal to add a simple option to allow this.

Adding this little option in the settings will keep everyone happy and on track.
If any custom font breaks the application, you can set the option to the forced specified font and the users will be able to swap this option if they want.

**Comment by DerTyp7214** [comment]
cant add option, there are 2 ways, system font or not. and we choose to not since too manye people use fucked up fonts.

**Comment by xerta555** [comment]
> cant add option, there are 2 ways, system font or not. and we choose to not since too manye people use fucked up fonts.

A decision based on a vote would have been perfectly understandable, a lie based on a simple refusal to add an option is not.
If you had told me that you lacked the time and/or inclination to code this option, i could have completely understood that.

**Comment by DerTyp7214** [comment]
not a lie, reflection is not a option for this app. so there you have 2 ways. xml font or not. thats it

**Comment by xerta555** [comment]
reflection ???

**Comment by DerTyp7214** [comment]
read about it, then youll understand

**Comment by xerta555** [comment]
You say to me that you use a sort of SDK on this app which don't support multiple fonts usage ?

**Comment by DerTyp7214** [comment]
bruh, if you dont know how to code dont complain or say what to do

**Comment by DerTyp7214** [comment]
if you really want it, do it without reflections and ill may merge it.
