### ISSUE TITLE
Theme not changing

### ISSUE THREAD

**Issue by CrossyAtom46** [DerTyp7214/RboardThemeManagerV3#254]
I used that app too many months after updating Gboard i couldn't change themes when i change it reverts back to system default theme

My Gboard version: version 12.7.10.507749191-beta-arm64-v8a

**Comment by DerTyp7214** [comment]
Ask in the [support group](https://t.me/gboardthemes/1)

Provide more Infos like your os, phone manufacturer and model name, location (some locations block certain things)

**Comment by CrossyAtom46** [comment]
I don't have telegram i don't want to give my phone number to telegram.
Device pixel 3a XL
Android 11

**Comment by DerTyp7214** [comment]
strange that it happens on stock, might be that you have to fix your flags.

[Fix flags](https://t.me/rkbdigboard/1516)

[Download link from message](https://t.me/gboardthemes/1/316858)

if this doesnt help, try turning "use magisk" off in rboard settings

**Comment by CrossyAtom46** [comment]
Sorry for not telling first

**Comment by CrossyAtom46** [comment]
i was able to use it with that rom
After the gboard update it's gone

**Comment by DerTyp7214** [comment]
try no magisk mode

**Comment by DerTyp7214** [comment]
> There is only 1 magisk module that i never tried with it: Safety Net Fix i added that recently can that be a problem?

maybe

**Comment by DerTyp7214** [comment]
i dont know much what can cause problems or can be a fix

**Comment by CrossyAtom46** [comment]
Tried ut without magisk module and its working right now (except auto dark and light themes). Please fix that on new update

**Comment by DerTyp7214** [comment]
you cant use auto dark / light without magisk. nothing to fix
