### ISSUE TITLE
Enter button + spacebar does not change colour

### ISSUE THREAD

**Issue by deltaxsingh** [DerTyp7214/RboardThemeManagerV3#453]
Only for completely black themes the enter button always defaults to blue. And the spacebar "outline" and lettering never appear.

This has been going on for years but I finally reinstalled this app and realized it's still not fixed.

Screenshot attached.

Android 13
Latest gboard as of this date. 
Samsung 22
Canada 

![Screenshot_20231006_232626_Vivaldi Browser](https://github.com/DerTyp7214/RboardThemeManagerV3/assets/28495838/3cb6432b-9dbe-4c28-850f-e7df8d1569ef)

**Comment by DerTyp7214** [comment]
This has nothing to do with the manager, that's a theme issue then.
