### ISSUE TITLE
Keyboard sound isn't changing.

### ISSUE THREAD

**Issue by siiidhan** [DerTyp7214/RboardThemeManagerV3#750]
I'm not able to change the clicking sound of my Gboard on Galaxy Note9 (with S22 Ultra OneUI 6 Port ROM)

Even after reboot, the sound doesn't change.

Note: I have selected the Magisk method at the setup process.

**Comment by AkosPaha01** [comment]
Sounds only works on AOSP ROM and it will be removed from Rboardbol because of it.
